Profile/urls.py
from django.urls import path
from . import views
from django.contrib import admin
#from django.contrib.auth import login,logout
from django.contrib.auth import views as authviews

app_name = 'Profile'

urlpatterns=[
    path('', views.view_profile, name='profile_view'),
    path('edit', views.edit_profile, name='profile_edit'),

]

home/urls.py
from django.urls import path, reverse
from . import views
from Account.views import login_view, signup_view, logout_view, dual

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', login_view, name='login'),
    path('signup', signup_view, name='signup'),
    path('logout', logout_view, name='logout'),
]

Profile/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
# from Account.models import RBCUser
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import post_save
from django.template.base import kwarg_re


# content_room= ContentType.objects.get_for_model(RBCUser.room_number)
# content_year=ContentType.objects.get_for_model(RBCUser.year)

# permission = Permission.objects.create(
#    codename='can_edit',
#    name='can edit profile account',
#    content_type=[content_room,content_year],
# )

# User = get_user_model()

# @login_required
class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='MessDetails', on_delete=models.CASCADE)
    # room_number = models.ForeignKey('Account.RBCUser.room_number', on_delete=models.CASCADE)
    #username = models.ForeignKey(settings.AUTH_USER_MODEL,default=user, on_delete=models.CASCADE)
    veg = models.BooleanField(default=False)
    meal_status = models.BooleanField(default=False)
    veg_on_egg = models.BooleanField(default=False)
    veg_on_fish = models.BooleanField(default=False)
    veg_on_chicken = models.BooleanField(default=False)
    veg_on_mutton = models.BooleanField(default=False)
    fine = models.IntegerField(blank='', null='', default='0')
    Updates_On = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

Profile/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from Account.models import RBCUser
from .models import UserProfile
from django.contrib.auth import get_user_model

User= get_user_model()

class Profile_edit_form(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude =[
            'user',
            'fine',

        ]

Profile/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from home.models import Hostel
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.contrib.auth import (
    get_user_model,
)
from django.contrib.auth.decorators import login_required
from .forms import Profile_edit_form
from .models import UserProfile

# Create your views here.

User = get_user_model()


@login_required(login_url='/login')
def view_profile(request):
    hostel = get_object_or_404(Hostel, slug="RBC")
    profile = get_object_or_404(UserProfile, user=request.user)
    title = str(request.user) + " Profile"
    context = {
        "title": title,
        'hostel': hostel,
        'user': request.user,
        'User':profile,
    }
    return render(request, 'profile/profile.html', context)


@login_required(login_url='/login')
def edit_profile(request):
    hostel = get_object_or_404(Hostel, slug="RBC")
    title = "edit " + str(request.user) + " Profile"
    profile = get_object_or_404(UserProfile, user=request.user)
    context = {
        "title": title,
        'hostel': hostel,
        'user': request.user,
        'User': profile,
    }
    if request.method == "POST":
        form = Profile_edit_form(request.POST, instance=profile)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect('/profile')
    else:
        form = Profile_edit_form(instance=profile)
        context = {
            "title": title,
            'hostel': hostel,
            'user': request.user,
            'form': form,
            'User': profile,
        }
    return render(request, 'profile/edit_profile.html', context)

Profile/templates/profile/edit.html
{% block title%}
edit
{%endblock%}

Profile/templates/profile/edit_profile.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}

{% block title%}
{{title}}
{%endblock%}

{% block preloader %}

{% endblock %}
{% block nav%}

{% endblock %}
{% block body %}

<div class="container">
    <h2>Profile</h2>
    <br>
    <div class="row">
    <div class="col-md card">
        <div class="card-header"><p>User:<b> {{user}}</b></p></div>
        <div class="card-body">
            <p>First Name: {{user.first_name}}</p>
            <p>Last Name: {{user.last_name}}</p>
            <p>Room Number:{{user.room_number}}</p>
            <p>Year: {{user.year}}</p></div>
        <div class="card-footer"><b>Fine:</b> {{User.fine}}</div>
    </div>
    <div class="col-md">
        <h2>Edit you Profile</h2>
        <form method='POST'>
            {% csrf_token %}
            <table>
                {{ form}}
                <tr>
                    <td></td>
                    <td>
                        <button type='submit' class="btn btn-primary">Submit</button>
                    </td>
                </tr>
            </table>
            <form>
    </div>
    </div>
</div>


{% endblock %}

{% block script %}

{% endblock %}

Profile/templates/profile/profile.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}

{% block title%}
{{title}}
{%endblock%}

{% block preloader %}

{% endblock %}
{% block nav%}
    <a class="nav-link" href="{% url 'home:logout' %}">Logout</a>
{% endblock %}
{% block body %}

<div class="container">
    <h2>Profile</h2>
    <br>
    <div class="row">
        <div class="col-md">
            <p>User: <b>{{user.username}}</b> </p>
        </div>
        <div class="col-md">
            <a class="" href="{% url 'Profile:profile_edit' %}">Edit your profile</a>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md">
            <ul>
                <li class="list-group-item"><b>First Name:</b> {{user.first_name}}</li>
                <li class="list-group-item"><b>Last Name:</b> {{user.last_name}}</li>
                <li class="list-group-item"><b>Room Number:</b>{{user.room_number}}</li>
                <li class="list-group-item"><b>Year:</b> {{user.year}}</li>
            </ul>
        </div>
        <div class="col-md">
            <ul>
                <li class="list-group-item"><b>Fine:</b> {{User.fine}}</li>
                <li class="list-group-item">veg: {{User.veg}}</li>
                <li class="list-group-item">veg on gg: {{User.veg_on_egg}}</li>
                <li class="list-group-item">veg on fish: {{User.veg_on_fish}}</li>
                <li class="list-group-item">veg on chicken: {{User.veg_on_chicken}}</li>
                <li class="list-group-item">veg on mutton: {{User.veg_on_mutton}}</li>
                <li class="list-group-item">meal status:
                    {% if User.meal_status == True %}
                        <b>ON</b>
                    {% else %}
                        <b>OFF</b>
                    {% endif%}
                </li>
            </ul>
        </div>
    </div>
</div>


{% endblock %}

{% block script %}

{% endblock %}