Account/urls.py
from django.urls import path
from . import views
from django.contrib import admin
#from django.contrib.auth import login,logout
from django.contrib.auth import views as authviews

app_name = 'Account'

urlpatterns=[
    path('login', views.login_view, name='login'),
    path('signup', views.signup_view, name='signup'),
    #path('logout', authviews.logout, {'template_name':'profile/logout.html'}, name='logout'),
    #path('edit', views.edit, name='edit'),
]

Profile/urls.py
from django.urls import path
from . import views
from django.contrib import admin
#from django.contrib.auth import login,logout
from django.contrib.auth import views as authviews

app_name = 'Profile'

urlpatterns=[
    path('', views.view_profile, name='profile_view'),
    path('edit', views.edit_profile, name='profile_edit'),

]

home/urls.py
from django.urls import path, reverse
from . import views
from Account.views import login_view, signup_view, logout_view, dual

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', login_view, name='login'),
    path('signup', signup_view, name='signup'),
    path('logout', logout_view, name='logout'),
]

mess/urls.py
from django.urls import path

from . import views

app_name = 'mess'

urlpatterns=[
    path('', views.home, name='home')
]

templates/amp_base.html
{% load static %}
{% load staticfiles %}
<!doctype html>
<html amp lang="en">
  <head>
    <meta charset="utf-8">
    <script async src="https://cdn.ampproject.org/v0.js"> </script>
    <title>{% block title%}{%endblock title %}|Rishi Bankim Chnadra Hall</title>
      <link rel="shortcut icon" href="{{hostel.Hostel_logo.url}}">
    <link rel="canonical" href="http://example.ampproject.org/article-metadata.html">
    <link rel="stylesheet" href="{% static "css/materialize.css" %}">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <script src="{% static "js/jquery-2.1.1.min.js" %}"></script>
    <script src="{% static "js/custome.js" %}"></script>
    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "NewsArticle",
        "headline": "Open-source framework for publishing content",
        "datePublished": "2015-10-07T12:02:41Z",
        "image": [
          "logo.jpg"
        ]
      }
    </script>
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
     {%block style%}
     {%endblock %}
  </head>
  <body>
    {% block preloader %}
    {% endblock %}
    <nav>
      <div class="nav-wrapper">
          <a href="#" class="brand-logo"><amp-img src="{{hostel.Hostel_logo.url}}" alt="{{hostel.Hostel_short}}" height="60" width="60" ></amp-img></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="{% url 'home:index' %}">Home</a></li>
        <li><a href="{% url 'mess:home' %}">Mess</a></li>
        <li><a href="{/net}">Net</a></li>
            <li><a href="{% url 'Account:signup' %}">Login/Signup</a></li>
            <li><a href="/admin">Admin</a></li>
      </ul>
      </div>
    </nav>
    <div class="container">
        <!-- <div class="card-panel light-blue darken-2" align="center"><h5>Rishi Bankim Chandra Hall</h5></div> -->
    {% block body %}
    {% endblock %}
    </div>

  <!-- Latest compiled JavaScript -->
    <script src="{% static "js/materialize.min.js" %}"></script>
    {% block script %}

    {% endblock %}
  </body>
</html>

templates/base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}{%endblock title %}|Rishi Bankim Chnadra Hall</title>
    <!-- Latest compiled and minified CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link rel="shortcut icon" href="{{hostel.Hostel_logo.url}}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static "css/modern-business.css" %}" rel="stylesheet">
    <link href="{% static "css/custome.css" %}" rel="stylesheet">
    {%block style%}
    <meta name="description" content="{{head_des}}">
    <meta name="author" content="{{author}}| Sarbesh Kumar Sarkar">
    {%endblock %}
</head>

<body>
 <nav class="navbar fixed-top navbar-expand-lg bg-dark navbar-dark">
         <a class="navbar-brand custombrand" href="{% url 'home:index' %}">
             <span><img src="{{hostel.Hostel_logo.url}}" alt="{{hostel.Hostel_short}}" style="width:50px;"></span>
             <span>Rishi Bankim Chandra Hall</span>
         </a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="collapsibleNavbar">
             <ul class="navbar-nav ml-auto">
                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'home:index' %}">Home</a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'mess:home' %}">Mess</a>
                 </li>
                 {% block nav %}
                 {% if request.user.is_anonymous == False %}
                 <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">{{user}}</a>
                     <div class="dropdown-menu">
                         <a class="dropdown-item" href="{% url 'Profile:profile_view' %}">profile</a>
                         <a class="dropdown-item" href="{% url 'home:logout' %}">Logout</a>
                     </div>
                 </li>
                 {% else %}
                 <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Signup/Login</a>
                     <div class="dropdown-menu">
                         <a class="dropdown-item" href="{% url 'home:signup' %}">Signup</a>
                         <a class="dropdown-item" href="{% url 'home:login' %}">Login</a>
                     </div>
                 </li>
                 {% endif%}
                 {% endblock %}
                 <li class="nav-item">
                     <a class="nav-link" href="/admin">Admin</a>
                 </li>
             </ul>
         </div>
 </nav>
{% block body %}
{% endblock %}
 <!-- Footer -->
 <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Rishi Bankim Chandra Hall 2018</p>
      </div>
      <!-- /.container -->
 </footer>
     <!-- Latest compiled JavaScript -->

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    {% block script %}

    {% endblock %}
</body>
</html>